### ISSUE TITLE
Artifact setting - possiblity to read version from app.json

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#1018]
From what I can tell from the AL-Go PS Code, the artifact settings always needs to contain a version number. Any chance this version can be read from the app.json files in a project? When multiple versions are available, the highest should be used.

**Comment by dsaveyn** [comment]
> If you specify the setting
> 
> ```
>     "UpdateDependencies": true
> ```
> 
> Then AL-Go will determine which version is the earliest version supported by all apps and use this. It will however also update all dependencies in the apps during build to have a dependency to the versions used for building.
> 
> Let me know if this behavior is what you are looking for

This is not really what we want: we only want to able to specify that the used artifacts should be the ones of the project app with the highest dependency. The dependency version should not be updated since we do this manually when necessary.

Now our artifact settings looks as following for one of our projects:

`"artifact": "//23.1//latest"`

It would be nice if we could omit the 23.1 and the system determines automatically the version based on the highest dependency version of the apps in the project.

**Comment by freddydk** [comment]
We have heard about this requirement from other partners and the design we landed on for this is the following:

The artifact setting in your project settings file can now contain a `*` instead of the version number. This means that AL-Go for GitHub will determine the application dependency for your projects together with the `applicationDependency` setting and determine which Business Central version is needed for the project.
- `"artifact": "//*//latest"` will give you the latest Business Central version, higher than your application dependency and with the same major.minor as your application dependency.
- `"artifact": "//*//first"` will give you the first Business Central version, higher than your application dependency and with the same major.minor as your application dependency.
