### ISSUE TITLE
Is it possible to convert the .yaml files given by AL-GO git hub into azure devops style .yaml. 

### ISSUE THREAD

**Issue by ravindrai** [microsoft/AL-Go#1139]
Hello Team, 

we've forked the PTE template into azure devops and started running Create  APP .yaml , but it is giving the error , since it is designed for the Git Hub, do we have a way to convert the .yaml of github to azure devops style.

**Error**: 

![image](https://github.com/user-attachments/assets/f10a5d1b-d91c-4aa5-a554-676d25d9b30e)

Kindly please let us know how to approach the problem here.

**Comment by aholstrup1** [comment]
See #101

AL-Go for GitHub wasn't designed for Azure DevOps. Even if we convert the yaml files the underlying scripts wouldn't work because they also depend on running on GitHub. 

I'm afraid you'll either have to run your workflows on GitHub or use another managed devops solution to help with your Azure Devops builds.
