### ISSUE TITLE
[Enhancement]: Disable-AzureDataCollection in Delivery step for Azure Storage to improve performance

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/AL-Go#1171]
### Feature description

Hi!

I'm happy with how speed is improving in our pipelines which makes this "detail" stand out and kind of annoy me. :)

When we use Deliver to Azure Storage there is one step where this question pops up and it seems to wait for an answer for a minute:

![image](https://github.com/user-attachments/assets/bcd9ba91-16f2-42e8-a62c-0660df555933)

Would it be possible to add Disable-AzureDataCollection to the script (or maybe some other solution)?

I'll attach the full logs also. 
[logs.txt](https://github.com/user-attachments/files/16633675/logs.txt)

**Comment by freddydk** [comment]
I think this problem is already fixed in preview.
It really stems from the fact that we try to reuse an already installer AzureRM powershell module, which has this problem.
In preview (hence in the next version) we always use the Az.Storage powershell module.

Would it be possible for you to try out the preview version of AL-Go for GitHub to confirm that this is true?
