### ISSUE TITLE
[Question]: SendExtendedTelemetryToMicrosoft not used?

### ISSUE THREAD

**Issue by frottke** [microsoft/AL-Go#1200]
### Question

It looks like the setting ‘SendExtendedTelemetryToMicrosoft’ in v5.3 is not being used. Am I missing something here? Is this possibly a bug?

Just for some context -> I was looking for this setting to enable it because I wanted to make sure my second Application Insights resource was getting the same signals (just for some internal testing, not a real use case).

**Comment by aholstrup1** [comment]
It's definitely not used in AL-Go telemetry by design :) 

SendExtendedTelemetryToMicrosoft is a bccontainerhelper setting that we set on containerhelper if it is provided in the AL-Go settings (AFAIK). I don't think you'd be able to test if this setting works since it only relates to what telemetry is sent to Microsoft. As a partner you should be getting the same telemetry irrespective of whether this setting is true or false.
