### ISSUE TITLE
[Bug]: Update AL-Go System Files 401 Error (Remote Server Returned Error)

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/AL-Go#1265]
### AL-Go version

5.3

### Describe the issue

Running Update AL-Go System Files giving error: 

> The remote server returned an error: (401) Unauthorized. 
> 
> Unauthorized
> 
> ...retrying in 1 minute
> Retry failed as well
> The remote server returned an error: (401) Unauthorized. 
> 
> Unauthorized

Log files attached.
[logs_29684787120.zip](https://github.com/user-attachments/files/17395733/logs_29684787120.zip)

### Expected behavior

No Error

### Steps to reproduce

1. Select Action
2. Click Run Workflow
3. Select branch to run workflow from (tried main and current default branch).
4. Leave temple Repository blank
5. Leave Checkbox for Download latest from template directory checked
6. Leave Checkbox for Direct Commit, Unchecked.
7. Click Run Workflow.

**Comment by freddydk** [comment]
This is likely because your GhWorkflow PAT has expired.
Please try to update that secret and retry?

On the similar bug reported above, we did modify the code to give a more descriptive error - but you won't get that until you successfully update AL-Go System Files :-)

So, next time - it should tell you what to try.

**Comment by jonaswre** [comment]
Had the same issue. For me the pat was expired.
