### ISSUE TITLE
[Bug]: App.Json V24 to V25 issue

### ISSUE THREAD

**Issue by XPLJohnPalma** [microsoft/AL-Go#1279]
### AL-Go version

1

### Describe the issue

Hi everyone,

We've updated our AppSource extension from v24 to v25, and we encountered the issue below.
Need help to resolved this, thank you.

![Image](https://github.com/user-attachments/assets/9a2f12b6-8ad3-469c-a5dc-2b494d84bf9f)

App.Json  v24

![Image](https://github.com/user-attachments/assets/3ee967ab-ada8-4934-bd42-a85d9d849899)

App.Json v25

![Image](https://github.com/user-attachments/assets/061c9497-3e90-49a8-a9ac-272bd6ceca46)

### Expected behavior

Is this should not be included in the AppSourceCop Validation?

### Steps to reproduce

I change the version to 25 and removed _Exclude_ReportLayouts

**Comment by freddydk** [comment]
This is happening when you are building right? (not when doing AppSource Validation)

AL-Go for GitHub will always use your latest released version to do an upgrade test. This means that it will try to install the latest version and upgrade it when running CI/CD.

It sounds like your latest released version cannot be installed on v25 because of this dependency.

It is our recommendation that you run Test Next Major regularly, which would have showed that your app was incompatible with the next major - and it is our recommendation, if possible, that you update your app (while on v24) to be compatible with next major at all times, to not block upgrades.

At this time, you can do two things.

1. If possible, change the application dependency to v24 again - build the app and create a release, which works with 24 and 25 (right thing to do)

2. Create a setting called `"skipUpgrade": true` in your project settings file run your builds, release and remove the setting afterwards again (easiest thing to do).

**Comment by XPLJohnPalma** [comment]
_This is happening when you are building right? (not when doing AppSource Validation)_

**Yes it is in the Build**

![Image](https://github.com/user-attachments/assets/9f74b42a-e920-4cbc-8f43-760fb10f257c)
![Image](https://github.com/user-attachments/assets/6f252c69-7c0a-45b1-a7fd-e63e18262042)


_AL-Go for GitHub will always use your latest released version to do an upgrade test. This means that it will try to install the latest version and upgrade it when running CI/CD._

**Noted on this, thank you**

_It sounds like your latest released version cannot be installed on v25 because of this dependency._

**Nope, I can installed our latest  version to our Sandbox V25 environment, NOTE: (I have successfully download symbols and published in our Sandbox v25 when I removed _Exclude_ReportLayouts in the dependencies)**

_If possible, change the application dependency to v24 again - build the app and create a release, which works with 24 and 25 (right thing to do)_

**I tried to move the _Exclude_ReportLayouts back again in my dependencies with version 24**

![Image](https://github.com/user-attachments/assets/33d2c082-a814-46a6-9963-274cdcca0fbd)

**but I cannot successfully download the symbols from our v25 Sandbox**

**Here is the error:** 

![Image](https://github.com/user-attachments/assets/bdd5ea31-2e52-4fe2-be8a-254f6704631c)

**It seems that, the _Exclude_ReportLayouts has been removed/obsolete in BC v25**

**Comment by freddydk** [comment]
Yes, so you v24 version cannot be installed on BC v25 - I assume that your v24 version is your latest released version in AL-Go.

When you then try to create your v25 version - we will try to install the v24 version to see whether the upgrade works smoothly and since we cannot install the v24 version - that fails. Setting "SkipUpgrade": true will remove that behavior.

But if you think about it - for BC (and for your customers) it is important that your v24 version is compatible with v25 - and that your v25 version is compatible with v26 - else your app will be blocking the customer from upgrading until you release a new version. This is the reason why AL-Go behaves like this - we assume that your current version is compatible with Next Major (and there is a workflow you can run to test this). That is our recommendation for the future. For now - you can do with the SkipUpgrade setting.
