### ISSUE TITLE
[Bug]: CICD Build step fails on step Publishing Apps after adding an appsource dependency in app.json

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#1306]
### AL-Go version

6.0

### Describe the issue

Anything described below can be found in my public repo [dependency-demo](https://github.com/louagej/dependency-demo)

1. Start a new AL-GO Project (or see my public repository we're the issue is simulated)
2. Add a new app
3. add an app source dependency in the app.json
4. merge changes in the main branch
5. CICD Fails during the step `Publishing apps`
 
## The Error message

```
Unexpected error when running action.
Error Message: Extension compilation failed HelloWorld.al(9,21): error AL0185: Codeunit 'MOB Toolbox' is missing
StackTrace: at Invoke-ScriptInBcContainer, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 113
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 379
<- at Publish-BcContainerApp, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Publish-NavContainerApp.ps1: line 154 
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 941
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2359
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2328
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 2313
<- at <ScriptBlock>, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1057
<- at Run-AlPipeline, C:\ProgramData\BcContainerHelper\6.0.28\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 1019
<- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v6.0\RunPipeline\RunPipeline.ps1: line 391
<- at <ScriptBlock>, D:\a\_temp\7ead24ca-0110-4da7-8795-e51266c09aa6.ps1: line 3
<- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v6.0\Invoke-AlGoAction.ps1: line 17
<- at <ScriptBlock>, D:\a\_temp\7ead24ca-0110-4da7-8795-e51266c09aa6.ps1: line 2
<- at <ScriptBlock>, <No file>: line 1
```

### Expected behavior

Since the previous steps resolved and installed the dependencies and the app was compiled without any errors I would assume the publishing apps to the docker container during the build should also go well.

## Previous successful steps during build:

- Run microsoft/AL-Go-Actions/RunPipeline@v6.0
- Run D:\a\_actions\microsoft\AL-Go-Actions\v6.0\RunPipeline/../Invoke-AlGoAction.ps1
- Analyzing repository
- Locating previous release
- Parameters
- Pulling generic image
- Creating Container
- Resolving dependencies
- Installed Apps
- Installing app dependencies
- Compiling apps

## Failing Step

- Publishing apps

### Steps to reproduce

Anything described below can be found in my public repo [dependency-demo](https://github.com/louagej/dependency-demo)

**Comment by macel94** [comment]
Hi

this bug is currently blocking a deployment that is very important for my team and for our clients.
I have hit the same exact error in our github enterprise, but I cannot publicly share our code.
How can we help?
Do you need an official ticket or something to solve this issue?

This could enable us to show that AL-GO is viable and empower not only this client but also many others inside our tenant.

Please reach out to me if you need another example for the bug and we may share details privately.

**Comment by jonaswre** [comment]
This is a very common issue. 

The reason is AL-Go can't download runtimes from the AppSource. AL-Go only downloads Symbols which cant be installed in a container. If you want you use AppSource Dependencies you need to add doNotPublishApps to true and useCompileFolder to true. This means no container is created but this will only compile your apps no tests are run. 

And as I found out lately you will also need to use signing using the "new" KeyVault signing. 

If you are able to get the runtime dependency directly from the vendor. There is a way to disable the Microsoft trusted feed. This would be necessary if you need to run tests. 

All in all a bad experience. I think it's the 5-6 Issue with the exact same error.

**Comment by jonaswre** [comment]
I think the reason it's shown like this is because installing the symbols is skipped silently and when compiling the app the symbols are present in the correct location but when you try to publish the app the dependency is missing.

**Comment by louagej** [comment]
Indeed a common issue.
But the advise to put `doNotPublishApps` to `true` and `useCompileFolder` to `true` has its downside.
Since you're not creating your docker container with a running BC instance, you won't be able to install and run you tests.
This is of course not what I wanted to achieve.
So, I got access to the runtime apps from our ISV-partner and added disabled the Microsoft trusted feeds in my `.github\AL-Go-Settings.json`:

```json
  "doNotTrustMicrosoftFeeds": true,
  "installOnlyReferencedApps": false,
  "installApps": [
    "https://linktomyruntimeapp.zip"
  ],
```

or if you downloaded the app(s) in a folder of you project

```json
  "doNotTrustMicrosoftFeeds": true,
  "installOnlyReferencedApps": false,
  "installApps": [
    "MyAppFolder\\MyDependeciesFolder\\"
  ]
```

**Comment by jonaswre** [comment]
> or if you downloaded the app(s) in a folder of you project
> 
>   "doNotTrustMicrosoftFeeds": true,
>   "installOnlyReferencedApps": false,
>   "installApps": [
>     "MyAppFolder\\MyDependeciesFolder\\"
>   ]

Not sure what you meant by this. But its not recommended to add .app files to your source repo. Just to clarify.

I had a customer once that did that and ended up with a repo that was almost 10 GB in size which made it horrible to work with. And fixing this messed up there git history pretty badly.

**Comment by louagej** [comment]
I know, but thanks for the advise
