### ISSUE TITLE
[Bug]: Experimental feature "git submodules" seems to be a breaking change (in some ways)

### ISSUE THREAD

**Issue by frottke** [microsoft/AL-Go#1344]
### AL-Go version

v6.1

### Describe the issue

We have identified a potential bug in version 6.1: all submodules, regardless of their location within the repository, are being downloaded during the git checkout process.

To provide some context, our repository’s root folder contains a Git submodule for internal scripts, which serves as a convenient way to update them globally. Unfortunately, the workflow attempts to download this submodule, despite not having the necessary permissions to do so.

I truly appreciate all the new features, especially experimental ones. However, would it be possible to "hide" such features behind a feature flag or check?

If needed, I would be happy to grant access to a repository where this issue can be reproduced.

### Expected behavior

We would have expected that only app/project paths are checked for Git submodules, rather than the entire repository. Alternatively, it would be helpful if authentication could be configured specifically for submodules.

### Steps to reproduce

first variation: create a submodule that is not in an configured app/project path then run CI/CD or PR Build. See that the git submodules is cloned.
second variation: create a submodule where git (cli, github_token) has no permissions to access the repository. It looks like that GHTOKENWORKFLOW is not used.

**Comment by freddydk** [comment]
Got it.
We cannot really use the GhTokenWorkflow for this as we need to clone the repo in order to get to the settings / secrets.
But... - I see that this change will break you when having submodules, which the standard github token cannot access.

We will investigate what we can do about this - in the meantime, you would have to revert back to v6.0 - then we will have a look at what we can do for this.

**Comment by frottke** [comment]
Thank you Freddy for the, as always, quick response! :)
We’ve already rolled back to v6.0, knowing this would be not a fast fix.

**Comment by frottke** [comment]
One more remark: Isn't every repository other than the current one out of scope for the default github_token? In other words, how should a submodule repository be configured to make it accessible? Currently, I don't see any other option except granting additional permissions to the checkout action (GitHub token).

**Comment by dibyanugraha** [comment]
How do you structure your repos? If they reside in the same organization, you can use relative path instead of full url path in your submodule.

My apologies I have to refer to outside blog, but this blog gives a good example how to change your submodule into relative path (given with above circumstances): https://www.damirscorner.com/blog/posts/20210423-ChangingUrlsOfGitSubmodules.html

**Comment by freddydk** [comment]
@dibyanugraha - I don't think the github token from one repository would be able to pull the submodule of another repository even with relative urls.
The default github token has very limited permissions I think

**Comment by freddydk** [comment]
Just tested this - for private repositories, we need an auth token on the actions/checkout - the default github.token won't suffice.
Currently, we do not have a token for use at that time, so we will have to refactor the support for submodules if we are to support that.

**Comment by dibyanugraha** [comment]
Yes, we can pass token to the checkout itself, but unfortunately the github_token workflow won't be suffice. It must be a security token variable in GitHub that has 'Read' access to submodule repositories.

**Comment by freddydk** [comment]
I will check if there is an easy way to support submodules with this knowledge - else we will have to pull the experimental support at this time.
