### ISSUE TITLE
Create localDevEnv with appDependencyProbingPaths

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#160]
I have setup a dependency to another app in another repo using the appDependencyProbingPaths. When I am running the localDevEnv.ps1 to create a new container, I am getting an error - after the container is created - that it can't download the dependency.

I have been reviewing the code and it seems that the downloading of the dependencies through the appDependencyProbingPaths is happening in the RunPipeline.ps1, but this isn't called from localDevEnv.ps1. The localDevEnv.ps1 calls the CreateDevEnv function and that does not seem to process the app dependencies.

I have made sure that the latest version of all the files is being used (I actually just created the repo). Am I doing something wrong or is this an issue?

**Comment by freddydk** [comment]
If you run Update AL-Go System Files and specify 

https://github.com/microsoft/AL-Go-PTE@preview (for PTEs)
or
https://github.com/microsoft/AL-Go-AppSource@preview (for App Source Apps)

Then this should now be supported.

- If the repository specified in appDependencyProbingPaths is public, then you don't need to specify an AuthTokenSecret
- If you have your secrets in a KeyVault, then you (the user running localDevEnv.ps1) should have access to that keyvault in order to read the secret in the KeyVault.
- If you do not have your secrets in a KeyVault, the script will attempt to use gh auth status to retrieve a GitHub token for downloading, if you are not logged in with gh - you can use another command prompt to perform the login.

**Comment by pzentner** [comment]
I have found some time to test it now. What I found is that there is an error and here is the message:

Error: The specified module 'C:\src\github\freddydk\AL-Go-Actions\Github-Helper.psm1' was not loaded because no valid module file was found in any module directory.
Stacktrace: at <ScriptBlock>, [..]\.AL-Go\localDevEnv.ps1: line 54
at <ScriptBlock>, <No file>: line 1

It seems like you forgot to remove those:

$GitHubHelperPath = "C:\src\github\freddydk\AL-Go-Actions\Github-Helper.psm1"
$ALGoHelperPath = "C:\src\github\freddydk\AL-Go-Actions\AL-Go-Helper.ps1"

I did this temporarily in my repo and it worked then without a problem.

**Comment by freddydk** [comment]
Ouch - will fix that right away, thanks

**Comment by freddydk** [comment]
Shipped in v2.0
