### ISSUE TITLE
Running CI/CD - PostProcess

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#216]
When running CI/CD, it all goes through, but the "PostProcess" fails in "Finalize the workflow" with the error:  "Unexpected error when running action (Cannot bind argument to parameter 'telemetryScopeJson' because it is an empty string.)".

This is happening currently in the preview version - in PTE and AppSource App for me.

I did not set "PartnerTelemtryConnectionString" and also did not set "SendExtendedTelemetryToMicrosoft".

**Comment by freddydk** [comment]
I think I can repro this.
Do you have this annotation in the builds?
![image](https://user-images.githubusercontent.com/10775043/193601692-7c8865e9-369a-48d3-9c6b-94fa9d051326.png)

Then GitHub thinks that there are secrets in the telemetry scope.
Of course the post process shouldn't fail anyway, but this is probably the reason.

**Comment by btaylor010110** [comment]
Freddy, I am running into the same issue and can confirm that the warning is issued in the Initialization.

![Screenshot 2022-10-03 113040](https://user-images.githubusercontent.com/54638136/193617032-25e76b93-4d7e-4e98-a6de-945f8faf11ea.png)

**Comment by pzentner** [comment]
> Do you have this annotation in the builds? ![image](https://user-images.githubusercontent.com/10775043/193601692-7c8865e9-369a-48d3-9c6b-94fa9d051326.png)

Yes, I found this in the builds.

**Comment by freddydk** [comment]
The reason for this behavior is, that GitHub thinks that the telemetry scope will reveal one of the secrets in GitHub - and it is probably right - one of your secrets might contain the same string as part of the json string.
I have fixed the issue, so that it shouldn't fail anymore.
The real fix is to BASE64 encoding the telemetry scope, I will add that to the next version.
