### ISSUE TITLE
Error when evaluating 'strategy' for job 'Deploy'

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#244]
When CI/CD is running against the main branch after a pull request is completed, I am getting the following error:

"Error when evaluating 'strategy' for job 'Deploy'. .github/workflows/CICD.yaml (Line: 398, Col: 15): Error parsing fromJson,.github/workflows/CICD.yaml (Line: 398, Col: 15): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/CICD.yaml (Line: 398, Col: 15): Unexpected type of value '', expected type: Mapping."

This happens in the preview version of AL-Go-PTE.

The CI/CD runs fine against the PR, but not against main.

Any ideas?

I added you to the repo that has the issue so you can look at it, if needed.

**Comment by freddydk** [comment]
I now also know why.
The root cause of the problem is that your AZURE_CREDENTIALS secret is formatted like this:
```
{
  "clientId": "1152162516527",
  "clientSecret": "djokdu283424j2i4k2o3",
...
}
```

should be:
```
{ "clientId": "1152162516527", "clientSecret": "djokdu283424j2i4k2o3", ... }
```

Apparently, if the Secret contains newlines, then every line becomes a secret and thus { and } becomes secrets.

So, if you reformat your secret to be compressed json - then it should work as expected.

I will update AL-Go to give a warning if secrets contains newlines.
I will consider changing this to an error at a later point in time.

**Comment by freddydk** [comment]
What I didn't notice was, that there actually are two warnings in the output:
![image](https://user-images.githubusercontent.com/10775043/197147791-893909b9-809b-4d53-87a3-4cf23636a74f.png)

which is the reason why it cannot find environments.

**Comment by freddydk** [comment]
I did run a number of builds, and you will be able to see that - you can delete the builds if you need to.
Your repo is back on the preview AL-Go.

**Comment by pzentner** [comment]
I have changed the AZURE_CREDENTIALS and it's working now. 

Thank you for your assistance! Much appreciated!

**Comment by freddydk** [comment]
Preview will now fail if any of the secrets are wrongly formatted (which will cause issues down the road)
