### ISSUE TITLE
[Question] Creating runtime apps in CI

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#279]
I know there are some pending improvements to make creating runtime packages viable for all supported versions. 
But until this is done, is their anyway to at least create a runtime package for the version that was used in the ci? 

https://github.com/microsoft/AL-Go/blob/0f8b24a6101480a6521e157b81f8f1ada47c8177/Actions/RunPipeline/RunPipeline.ps1#L214

This makes me think there is currently no way. Will I need to fork Al-go to get this working?

**Comment by jonaswre** [comment]
Thanks alot.

Thats a good solution for now.

**Comment by freddydk** [comment]
BTW - the modernDev team is working on a feature, which enables me to create runtime packages without the need for a running container/service tier. This will greatly improve the performance and make us able to create runtime packages for all needed versions in minutes instead of hours - which is the reason for the wait...:-)
