### ISSUE TITLE
Automatic deployment to environment with annotation

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#520]
We have an added an environment that we do _not_ want to have automatic deployment for, but it deploys anyway.
We have annotated the environment, as stated in the blog post about deployment:

![image](https://github.com/microsoft/AL-Go/assets/8398485/e08470f9-cfd5-4029-a59e-186607291806)

The environment is named "next_release (only from release branch)".

I added a branch protection rule to only allow it from release/*, but that just means that CICD run will fail because it tries to deploy, but is not allowed to. 

![image](https://github.com/microsoft/AL-Go/assets/8398485/ec1d03bc-8124-4b10-8367-e3a3532dd2ef)

**Comment by freddydk** [comment]
If you add (PROD) to the name – it should be ignored.
It isn’t any annotation – it is these 4 annotations.

We will add functionality to the DeployTo setting to allow you to set branches, and whether or not to use this for continuous deployment, but for now – the poor mans solution is what works.



/Freddy

From: Aske Holst ***@***.***>
Sent: Tuesday, 9 May 2023 15.30
To: microsoft/AL-Go ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/AL-Go] Automatic deployment to environment with annotation (Issue #520)


We have an added an environment that we do not want to have automatic deployment for, but it deploys anyway.
We have annotated the environment, as stated in the blog post about deployment:

[image]<https://user-images.githubusercontent.com/8398485/237088927-e08470f9-cfd5-4029-a59e-186607291806.png>

The environment is named "next_release (only from release branch)".

I added a branch protection rule to only allow it from release/*, but that just means that CICD run will fail because it tries to deploy, but is not allowed to.

[image]<https://user-images.githubusercontent.com/8398485/237108642-ec1d03bc-8124-4b10-8367-e3a3532dd2ef.png>

**Comment by AskeHolst** [comment]
Thanks, postfixing with (FAT) solved the problem.
I would suggest changing the wording in the blog post, as it a primary source on how to set up deployment in Al-Go. The word "like" suggests that any annotation can be used.

Looking forward to the DeployTo setting.
