### ISSUE TITLE
Publish To AppSource fails with "unable to locate apps"

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#567]
I'm using the latest microsoft/AL-Go-AppSource preview version.  When I run the "Publish To AppSource" action, I receive the following error in the Deliver step:

```
Using Azure.Storage version 2.1.0
Attempting authentication to https://api.businesscentral.dynamics.com/.default using clientCredentials...
Authenticated as app ***
AppSource MainAppFolder .\OfficeProducts
Error: Deliver action failed. Error: Internal error - unable to locate apps Stacktrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 430 at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\preview\Deliver\Deliver.ps1: line 99 at <ScriptBlock>, D:\a\_temp\0d7350a8-556b-49bf-9c5b-f06944c1e9e4.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: Deliver Telemetry Correlation Id: 2d4b109a-f51e-4726-b175-9151ff7e31c4
Removing BcContainerHelper
Error: Process completed with exit code 1.
```

Freddy, you have been invited to this repo previously and should have permissions, so the repo URL is https://github.com/BMI-Software/OfficeProducts-AppSource/

If you need further information, I'll try to answer quickly.  I will be traveling on business tomorrow through early next week, and I'll keep an eye out for any responses here.

Thanks!

**Comment by freddydk** [comment]
Thanks, will have a look tomorrow morning.

**Comment by freddydk** [comment]
Tried to Update the AL-Go System files to a debug version of AL-Go.
Then I didn't get the same error.
I have now switched back to microsoft/AL-Go-AppSource@preview - and I also do not get the same error.
I now get this error:
![image](https://github.com/microsoft/AL-Go/assets/10775043/bf33cab7-1302-4005-87ca-46cb4dbf7762)
Which is caused by the AuthContext for AppSource is made with the wrong scope.
When you fix that it should work.

One question - in this dialog:
![image](https://github.com/microsoft/AL-Go/assets/10775043/e6a9b2e2-6d3c-4071-958f-ce8f3e8f2cc7)

Do you change any values when running?

**Comment by BMI-Mike** [comment]
I only changed the last value "Promote Appsource App" to Y.

**Comment by rbability** [comment]
We had the same issue and fixed it by adding
`"scopes":"https://api.partner.microsoft.com/.default"`
to the APSOURCECONTEXT Secret JSON.

Maybe that helps.

**Comment by freddydk** [comment]
Use workflow from: <main> really just means where should you run the code from.
If you select a release branch or like in the drop down. you will be running an older version and you don't really want that.

On the error - it looks like you have specified the appId from app.json as your appSourceProductId.
That is wrong, you should follow these guidelines: https://github.com/microsoft/AL-Go/blob/main/Scenarios/settings.md#appsource-specific-basic-settings
