### ISSUE TITLE
Error when i run localDevEnv.ps1

### ISSUE THREAD

**Issue by ingebruvik** [microsoft/AL-Go#61]
I get the error below when i run the localDevEnv.ps1 step 
I tried to run the Import-Module Microsoft.PowerShell.Archive but that did noe help me.,
Any ideas about what is causing my problem?

Downloading BcContainerHelper latest version
Using Expand-Archive
Expand-7zipArchive : The 'Expand-Archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
At C:\Users\bruviki\AppData\Local\Temp\tmp30E3.tmp.ps1:253 char:9
+         Expand-7zipArchive -Path "$tempName.zip" -DestinationPath $te ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [Expand-7zipArchive], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,Expand-7zipArchive

**Comment by freddydk** [comment]
Could you try to run:

Import-Module Microsoft.PowerShell.Archive

on your machine?
Which error is returned?

Thanks

**Comment by freddydk** [comment]
In the end, there is something wrong with the machine - or some module installed, which prevents Expand-Archive to run.
You can also download and install 7zip (from https://www.7-zip.org/download.html), then the code will bypass Expand-Archive (and be faster).

**Comment by ingebruvik** [comment]
I get no error when i run the Import-Module Microsoft.PowerShell.Archive command.
I will try to download and install 7zip and see what happens then.

**Comment by BW-PA** [comment]
I encountered the same error when running localDevEnv.ps1 
```
Expand-7zipArchive : The 'Expand-Archive' command was found in the module 'Microsoft.PowerShell.Archive', but the module could not be 
loaded. For more information, run 'Import-Module Microsoft.PowerShell.Archive'.
```

When I run Import-Module Microsoft.PowerShell.Archive I get the following error

```
Import-LocalizedData : Cannot find the Windows PowerShell data file 'ArchiveResources.psd1' in directory 
'C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\en-GB\', or in any parent culture directories.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:28 char:1
+ Import-LocalizedData  LocalizedData -filename ArchiveResources
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\WINDOWS\syst...eResources.psd1:String) [Import-LocalizedData], PSInvalidOperationExcep  
   tion
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

I have 7zip installed

**Comment by BW-PA** [comment]
Interestingly, when I run localDevEnv.ps1 within a standalone powershell window I don't get the error and it uses 7zip
![image](https://user-images.githubusercontent.com/78051738/160059958-ab6e577c-026f-4712-96f5-2027a66d01a6.png)

So it seems the error only occurs when running localDevEnv.ps1 from within VSCode integrated powershell terminal.

**Comment by freddydk** [comment]
@BW-PA thanks for the explanation

**Comment by gunnargestsson** [comment]
Same here, works in Powershell but not in the terminal section of VS Code.

**Comment by BusinessCentralGeek** [comment]
Hi, I can´t get pass 'Removing BcContainerHelper' step. Tried from VSCode terminal and from PowerShell with no luck. The image is pulled but the problem is building the container. Tried running 'uninstall-module bccontainerhelper' before the scipt but with no luck.

![image](https://user-images.githubusercontent.com/92911762/162965790-58daac20-7843-4fb2-9a8b-b22c6a4ce91c.png)

**Comment by freddydk** [comment]
That seems to be a local problem - a restart of the host will probably solve this.

**Comment by BusinessCentralGeek** [comment]
This is the error from VSCode: **Service Tier doesn't exist / is not installed**

![image](https://user-images.githubusercontent.com/92911762/163007571-67165f87-acb4-4b05-a605-c97a804f6e60.png)

**Comment by freddydk** [comment]
On the original error (@ingebruvik, @BW-PA and @gunnargestsson) in this issue, v1.2 of AL-Go will spawn a new PowerShell window elevated when trying to run from VS Code - instead of using the VS Code runner.

on @BusinessCentralGeek - the localDevEnv now includes a text:

_NOTE: You need to have Docker installed, configured and be able to create Business Central containers for this to work.
If this fails, you can setup a cloud based development environment by running cloudDevEnv.ps1_

and I am also working on supporting ACIs (Azure Container Instances) and Azure VMs for people having problems running docker on their machine. Unfortunately, we are seeing an increasingly number of problems with defender and Windows 10 (even some Windows 11).
