### ISSUE TITLE
Equivalent of ForceSync for AL-Go?

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#625]
We had to renumber a group of fields to preserve TRANSFERFIELDS functionality. Of course we then get this error when checking the PR:

 Error: AS0002 The field with name <field name> and ID <ID> was found in the previous version, but is missing in the current extension. This might break the upgrade of existing installations.

If we are not "live" anywhere, but deployed only as Dev to a couple of cloud environments, is there a way to force through changes like these in AL-Go while the AppSource product is being evolved? Or better to create a new repo where no "previous version" is present?

**Comment by freddydk** [comment]
Currently in preview, the DeployTo structure now has support for SyncMode.
See: https://aka.ms/algosettings#deployto

**Comment by DesarrolloBC** [comment]
Hello Freddy,

Is this feature available? I tried setting it up, but when the deployment is done, it doesn't go for the setting and uses instead the "Add" SyncMode.

Here is my settings:


  "DeployToMy-MXSandboxTest": {
    "EnvironmentName": "MXSandboxTest",
    "Scope": "PTE",
    "continuousDeployment": false,
    "SyncMode": "ForceSync"
  }

And once the deployment is done, it fails, as it doesn't read the setting. Also the same happens when using Scope = PTE, it always uses Dev Scope.

This is the error code:

Publishing X_24.6.49.0.app to https://api.businesscentral.dynamics.com/v2.0/MXSandboxTest/dev/apps?SchemaUpdateMode=synchronize
Status Code 422 : Unprocessable Entity
No se puede actualizar la extensión NAV 'X by X 24.6.49.0' debido al error siguiente: 'TableExtension 70012 X :: No se encuentra el campo 'X'. No se permite quitar campos.
TableExtension 70001 X :: No se encuentra el campo 'X'. No se permite quitar campos.
TableExtension 70001 X :: No se encuentra el campo ''. No se permite quitar campos.

Publish-BcContainerApp Telemetry Correlation Id: 46daa3d6-839f-4729-953c-5d0a97b3567d
Error: Deploying to MXSandboxTest failed.  Status Code 422 : Unprocessable Entity
Error: Process completed with exit code 1.

Thanks.
