### ISSUE TITLE
Updating of Asset artifacts

### ISSUE THREAD

**Issue by buzzwick** [microsoft/AL-Go#714]
Can I get an explanation of how this particular piece of a repo is updated? I have done everything I can think of --new versions, new release, CI/CD--and still this Assets section remains stubbornly at the same version number. Which then will not deploy, because that version is already deployed. I find nothing specific in the workshop materials to explain how to make this section update:

<img width="903" alt="image" src="https://github.com/microsoft/AL-Go/assets/40246434/be79af0f-f2cb-4c3a-b78e-cca7501140e7">

**Comment by freddydk** [comment]
You might be in a catch-22 
All builds are marked as failing, meaning that we have a hard time locating the latest successful build.
You might need to remove the environments, in order to make a successful build.

Not sure whether we should check for successful builds instead of successful workflows instead - will discuss with the team

**Comment by buzzwick** [comment]
If you mean remove all the environments defined in Settings for this repo, I can do that. 
So the workflow is succeeding, but builds are failing? I will go back over the logs. Thanks.

**Comment by freddydk** [comment]
Did you find a solution to this?

**Comment by freddydk** [comment]
You should create a release when you release your app to production (that could be AppSource or a PTE in production).
When you create a release you can specify which version you want to promote to a release (default is latest).
The latest release becomes the "current" version - the current version is what is available to customers (on appsource or as a PTE)
When you publish to an environment, the default is current, but you can also specify latest to just publish the latest build to an environment.
You shouldn't run publish to environment with an environment, which is setup for continuous deployment - that one already has the app.

**Comment by buzzwick** [comment]
This is very helpful. 
We are publishing only to sandbox environments at this point. There are no Production environments live yet.
So maybe we should not bother with releases, and just publish using CD to those sandbox environments?

**Comment by freddydk** [comment]
> This is very helpful. We are publishing only to sandbox environments at this point. There are no Production environments live yet. So maybe we should not bother with releases, and just publish using CD to those sandbox environments?

Yeah - if you haven't released your app - you shouldn't create a release.
When you create a release, this is automatically used to check for breaking changes in the CI pipeline and will only cause problems really.

Either publish using CD - or manually, specifying latest or version number instead of current in the version field in Publish To Environment.

**Comment by buzzwick** [comment]
Got it. This will simplify things greatly. Thank you.
