### ISSUE TITLE
[Question] Self-hosted runner for non-build jobs?

### ISSUE THREAD

**Issue by fvet** [microsoft/AL-Go#735]
We're currently running our full CI/CD process through Azure Devops pipelines, using a dedicated Azure build server with several build agents. The average completion time of a build pipeline to compile an AL project is approx. 3 mins. (1 min of prep, +-2 min of compiling)

When looking into a fairly simple action / workflow on github - **not** including any build steps - I've noticed a large delay / long completion time of the non-build jobs. 

A simple PR (as a result of 'Update latest AL-Go files' to merge to main) results in below execution times (5m 53 s - compared to 1m on DevOps):
 
![image](https://github.com/microsoft/AL-Go/assets/25268332/9fba0e57-572f-4e42-82bc-b2a93d41975c)

I've seen #729, which refers to delays when using `[windows-latest]`, but even without this issue, the different jobs still seem to take longer than we're used to on Azure DevOps.

On organisation level, I've configured the use of self-hosted runners ...

![image](https://github.com/microsoft/AL-Go/assets/25268332/a6d0e32d-948a-4a40-9fb9-a81042872f50)

... but I'm not sure if these runners are solely used by the **build** jobs?

Looking in the workflow file, I see different 'runs-on' based on the type of job, which makes me think the runners are used by the **build** jobs only:

```
- runs-on: [ windows-latest ]
- runs-on: ${{ fromJson(matrix.os) }}
```

Question:
- Would it make sense to off-load **any** job (including the non-build jobs) to the self-hosted runners to have a performance gain (and decrease github billable time)? Is this supported by AL-Ops?

On https://github.com/microsoft/AL-Go/issues/529#issuecomment-1543849480, I found a comment about ...

> If you also want to use self hosted runners for non-build jobs, set "runs-on" to "selfhosted" as well and run Update AL-Go System Files.

... but not sure on where to set the 'runs-on' property (without actually customizing any of the templates).

**Comment by freddydk** [comment]
On the performance issue, I think it is very much related to GitHub hosted Windows runners, which is why we are going to change more and more to use Ubuntu-Latest for jobs which doesn't need a docker container.
Ubuntu-Latest is faster and half the price of Windows runners.

**Comment by dsaveyn** [comment]
A follow-up question related to the question of my colleague above.

The documentation mentions the following for the "runs-on" settings:

**Setting runs-on to ubuntu-latest will run all non-build jobs on Linux, build jobs will still run windows-latest (or whatever you have set in githubRunner)**

So we've set the settings to:

```
  "runs-on": "ubuntu-latest",
  "githubrunner": "self-hosted",
```

We've 2 self-hosted runners: 1 on linux, 1 on windows.

When the CI/CD workflow is run, it appears that builds are done using the ubuntu runner instead of the windows runner. I was expecting the windows runner to be used. 

![image](https://github.com/microsoft/AL-Go/assets/92365904/53850cda-5646-40e4-9561-e6766d5c21c6)

What am I missing here?
