### ISSUE TITLE
Error in workflows starting approx 2 hours ago.

### ISSUE THREAD

**Issue by BMI-Mike** [microsoft/AL-Go#746]
A parameter cannot be found that matches parameter name 'accept_insiderEula'.

I noticed there was an update to AL-Go and updated one of our repositories.  I now receive this error on CICD and other workflows that build containers.

**Comment by freddydk** [comment]
Are you setting a special version of BcContainerHelper in that repo?
The preview of AL-Go needs the preview of BcContainerHelper.
If you have a BcContainerHelperVersion setting in the repo, please remove it.

**Comment by BMI-Mike** [comment]
Let me try flipping all settings away from preview.  I had to use preview for a while to get the HSM code signing.   I should have thought about trying that first before opening an issue!   More to come.

**Comment by BMI-Mike** [comment]
I confirmed that going back to main (from preview) was the solution.  Sorry for the trouble.

**Comment by freddydk** [comment]
Well - preview should work as well.
The problem is probably that you have a hardcoded setting saying bcContainerHelperVersion: latest.
You should remove that setting and leave it to AL-Go to select BcContainerHelper (it might get you in trouble in the future).
Latest AL-Go uses latest BcContainerhelper and preview AL-Go needs preview BcContainerHelper.

**Comment by freddydk** [comment]
It will help me if you can confirm that you indeed have a hardcoded setting called BcContainerHelperVersion in your repo or in settings variables, thanks

**Comment by BMI-Mike** [comment]
You are correct. I had "bcContainerHelperVersion": "latest" in my AL-Go-Settings.json file.  I have now removed this hard-coded setting as suggested.
