### ISSUE TITLE
Error when evaluating 'strategy' for job 'Deploy'. .github/workflows/PublishToEnvironment.yaml

### ISSUE THREAD

**Issue by SusanneJansTwoday** [microsoft/AL-Go#825]
I have a problem like in this issue: https://github.com/microsoft/AL-Go/issues/244

I have an environment with an AUTHCONTEXT seceret setup without newlines in the Json.
Trying to publish my app to my GitHubTest environment, but the workflow fails: 
![image](https://github.com/microsoft/AL-Go/assets/124250941/e9ccebc4-a40b-4771-8dd3-d07dd0456fa4)

![image](https://github.com/microsoft/AL-Go/assets/124250941/f7e8dfa8-a67e-4fd2-8953-2eba509ced06)

**Comment by freddydk** [comment]
It looks like you have spaces or newlines in your secrets (maybe the authcontext is not compressed)?

**Comment by freddydk** [comment]
It might be another secret or an organizational secret accessible in this repo.
Looking at
![image](https://github.com/microsoft/AL-Go/assets/10775043/a5a34b79-f5e6-4a1d-ab2a-c9def356ab36)

You can see that everywhere where there is a { or a } - they are masked as three *'s
This happens when the brackets are considered secrets - and then everything falls apart.

**Comment by freddydk** [comment]
The issue comes from secrets being formatted as:

```
{
    "property": "value"
}
```

instead of

```
{"property":"value"}
```

Both are perfectly fine json - but the upper will cause issues.
I will do some investigations on whether we can avoid that.
