### ISSUE TITLE
CI/CD building apps with dependencies error "Property "AppId" cannot be found."

### ISSUE THREAD

**Issue by ninjaniels** [microsoft/AL-Go#836]
Hi! I am trying to follow the AL-Go workshop (https://github.com/microsoft/AL-Go/blob/main/Workshop/Index.md), but I'm encountering an error when attempting to run the CI/CD pipeline on a repo with multiple projects and dependencies between apps using packages to resolve dependencies.
The repo 'MySolution' has the apps 'W1', 'DK', and 'US'. 'W1' has a dependency to app 'Licensing' in repo 'Common'. The apps 'DK' and 'US' are dependant on 'W1'.

The app 'W1' builds using the deployed packages from repo 'Common', but the apps 'DK' and 'US' fail with error message "Property "AppId" cannot be found."

Here is the full output from the log, 
[Log.txt](https://github.com/microsoft/AL-Go/files/13480766/Log.txt)

![image](https://github.com/microsoft/AL-Go/assets/44019151/3895a7db-5c72-4da5-b3ab-859946cf8912)

**Comment by freddydk** [comment]
I did run into this bug myself last week - and will have a fix ready one of the next days.

**Comment by freddydk** [comment]
Just had a look - the issue is actually in BcContainerHelper and a new version has just been released (6.0.1), so your pipelines should work now when they discover the new version (this can take hours though)
If you want to expedite this, you can add a setting to the org settings variable called BcContainerHelperVersion and set it to preview - then it should work right away.

**Comment by ninjaniels** [comment]
Thanks, it's working as expected now. Btw, I have been looking for documentation on all of the different settings in the AL-Go-Settings.json. Is this available anywhere? Thanks again

**Comment by freddydk** [comment]
https://aka.ms/algosettings is reference for all settings
