### ISSUE TITLE
Preprocessorsymbols and clean build mode

### ISSUE THREAD

**Issue by SusanneJansTwoday** [microsoft/AL-Go#881]
Hi Freddy

I am trying to get activating a selection of preprocessorsymbols to work with AlGo.

If I build and deploy a project of 3 apps without any settings of preprocessorsymbols evrything works fine.
If I then add the following to the settingsfile the same CI/CD workflow fails:

"buildModes": [
    "Clean"
  ],
  "cleanModePreprocessorSymbols" : [
    "XX"
  ] 

the error is:

Error: Unexpected error when running action. Error Message: There is no artifacts present in D:\a\BC-Beta2\BC-Beta2\.artifacts matching *-main-Apps-<version>., StackTrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v4.0\Deploy\Deploy.ps1: line 75 <- at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v4.0\Deploy\Deploy.ps1: line 69 <- at <ScriptBlock>, D:\a\_temp\5bb10c37-b2cf-4173-acec-529cfaced4d4.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.

Note: Only one of the apps contain code that involves the symbol XX but all 3 apps must be included.

PS: I was the one with the question about adding buildmodes and preprocessor-symbols in DeployToXYZ-settings at your workshop the other day. Currently I am not adding the settings in DeployTo - this will be next step if we can make this work - and if you know that it is even possible. The goal is to control which environments will receive certain symbols activated.

Kind regards Susanne

**Comment by freddydk** [comment]
Hi, do I understand it right:
You have MyApp, which contains conditional code depending on pre-processor symbols (ex. FUNCA, FUNCB and FUNCC)
You want to compile the 3 versions of MyApp and deploy the one with FUNCA to environment ENV1, the one compiled with FUNCB to ENV2 and the one with FUNCC to ENV3.

If this indeed is that you want, then that is not supported at this time.

I assume that it would require us to add a buildMode to the DeployTo structure in order to know which buildMode app would be deployed to which environment.

**Comment by freddydk** [comment]
I think I got it, but yeah - let's setup half an hour next week to show me the process - feel free to invite and suggest a time to freddyk at microsoft dot com.
Sounds like you are controlling functionality using pre-processor symbols instead of using development branches (kind of).
