### ISSUE TITLE
Deployment with a free subsciption

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#971]
Hi,

I have a customer with a free GitHub subscription. So this means we can't create Environments to deploy to in the repository.
But as the documentation mentions, we can add an array to the `.github/AL-Go-Settings.json` file.

I did add this to my settings file:

```json
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@main",
  "environments": [
    "DEV",
    "UAT_20240216",
    "Production"
  ],
  "templateSha": "1e6ebb58fc629cc134759f996f9be9ab6ada7fb4"
}
```

I assumed the Production environment would be skipped as the `CI/CD` workflow doesn't deploy to production environments.
And the Production deployment should be done with the `Publish To Environment` workflow.
But apparently, this assumption isn't correct as all the environments got updated.

![image](https://github.com/microsoft/AL-Go/assets/7229592/9d8dd9d7-381f-4ed3-83fd-56c1543d4992)
 
Is this by design and do I have to remove the Production from the array or could this be improved in one of the coming updates?

**Comment by freddydk** [comment]
When you look into the environments - did it actually install the app in the environment?
27 seconds seems very fast - I assume that it states that it skips the environment because it is a production environment.
It doesn't fail per se (because then the build would be broken)
You can add this:

```
"DeployToProduction": {
    "ContinuousDeployment": false
}
```

to your settings - then it will be excluded from the CD altogether - but if this isn't stated, it needs to determine whether or not it is a prod environment.

**Comment by louagej** [comment]
@freddydk ,

I did not check on the Extension Management Page if the deployment was actually done... :flushed: sorry about that.
I was confused because of the green :white_check_mark: checkmark in the workflow summary.
But I added `DeployTo<<Environment>>` and then it's more clear there is no produciton deployment in the workflow summary:

```json
"DeployToProduction": {
    "ContinuousDeployment": false
}
```

![image](https://github.com/microsoft/AL-Go/assets/7229592/d847c9ea-a35e-4d36-96ad-e4c624771e94)
