### ISSUE TITLE
Workflow Update AL-Go System Files removes schedule in NextMajor.yaml and NextMinor.yaml

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#992]
Hi,

I changed the `.github/workflows/NextMajor.yaml` to run every sunday at 23:00

When I run the workflow `Update AL-Go System Files`, the [PR2](https://github.com/louagej/project1/pull/2/files) tries to remove this schedule.

![image](https://github.com/microsoft/AL-Go/assets/7229592/bdb179e3-5098-4d3c-bdbd-1f2203be6715)

Is it possible to let the workflow merge the file instead of overwriting it?

**Comment by aholstrup1** [comment]
That's because these things are controlled by settings in AL-Go. In this case you have to use the NextMinorSchedule and NextMajorSchedule settings. After you've added those settings you can run Update AL-Go System Files and the schedule should be added again 

You can read more here:
https://github.com/microsoft/AL-Go/blob/8dfde66bdf7b91d0d56d9a97f6f1688e444e067d/Scenarios/settings.md#basic-repository-settings

https://github.com/microsoft/AL-Go/blob/main/Workshop/ScheduledTestRuns.md
